name: MongoDB Integration

on:
  push:
    branches:
      - main

jobs:
  update-mongo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update MongoDB
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        npm install mongodb
        node -e "
        const { MongoClient } = require('mongodb');
        (async () => {
          const client = new MongoClient(process.env.MONGO_URI);
          await client.connect();
          const db = client.db('sampleupload');
          const collection = db.collection('users');
          await collection.insertOne({ message: 'GitHub Integration Test' });
          await client.close();
        })();
        "
