name: MongoDB Atlas Integration Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connect-and-query-mongo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MongoDB Shell 
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb.asc
        echo "deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh

    - name: Set up MongoDB connection
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        echo "Connecting to MongoDB Atlas..."

    - name: Connect to MongoDB and list collections
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        mongosh $MONGO_URI --eval 'printjson(db.getCollectionNames())'

    - name: Install Python and dependencies
      run: |
        sudo apt-get install -y python3 python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip install -U pip
        pip install -r requirements.txt

    - name: Set up ChromeDriver and Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Set Timezone to India Standard Time (IST)
      run: sudo timedatectl set-timezone Asia/Kolkata

    - name: Run Selenium tests and generate HTML report
      run: |
        pytest --html=report.html --self-contained-html > pytest_test_results.log || exit 0
        cat pytest_test_results.log

    - name: Check if tests passed or failed
      run: |
        if grep -q "FAILED" pytest_test_results.log; then
          echo "Tests failed"
          exit 1
        else
          echo "Tests passed"
        fi

    - name: Archive Pytest Results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: pytest_test_results.log

    - name: Archive HTML Test Report
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-report
        path: report.html
