name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd="curl --silent --fail localhost:27017 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest
        env:
          MONGO_URI: "mongodb://localhost:27017/sampleupload"  # Pass MongoDB URI if required for tests

      # Optionally, you can add an action to upload test results if necessary
      # - name: Upload test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest-results
      #     path: results/
