name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version

      - name: Set up Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB to start..."
            sleep 1
          done
          echo "MongoDB is ready"

      - name: Run Tests
        run: pytest

      - name: Shut Down Docker Compose
        if: always()
        run: docker-compose down

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: pytest_test_results.log

      - name: Send Email Notification
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "failure" ]; then
            python send_email_notification.py failure
          fi
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: antony.silvesta@nidrive.in
